changesetBaseRefs:
  - master
  - origin/master
  - upstream/master
  - main
  - origin/main
  - upstream/main

enableGlobalCache: true

nodeLinker: node-modules

npmScopes:
  gothub-team:
    npmAuthToken: "${NPM_AUTH_TOKEN:-none}"
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
