# This is a basic workflow to help you get started with Actions

name: Bump Version

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:
    branches: ['**','!master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    name: "Publish npm packages as release"
    runs-on: ubuntu-latest
    if: "github.repository_owner == 'gothub-team' && contains(github.event.head_commit.message, '[release]')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install
      run: yarn install
    - name: Bump Patch
      run: |
        git config --local user.email github-actions@github.com
        git config --local user.name github-actions
        yarn bump:patch
        git push
