# This workflow will do a clean install of node dependencies and run all test suites on node 14
name: Check Version
on:
    push:
        branches: ['**', '!master']
jobs:
    check-version:
        runs-on: ubuntu-latest
        if: "github.repository_owner == 'gothub-team' && !contains(github.event.head_commit.message, 'ci skip')"
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Check Version
              run: git log origin/master.. | grep "\[release\]"
