# This workflow will do a clean install of node dependencies and run all test suites on node 14
name: Check Version
on:
  push:
    branches: ['**']
jobs:
  check-version: 
    runs-on: ubuntu-18.04
    if: "github.repository_owner == 'gothub-team' && !contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check Version
      run: git log master.. | grep "\[release\]"