# This workflow will check linting with eslint in node 14
name: Linting
on:
  push:
    branches: ['**']
jobs:
  eslint: 
    runs-on: ubuntu-latest
    if: "github.repository_owner == 'gothub-team' && !contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: 17.x
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Lint
      run: yarn lint