# This workflow will do a clean install of node dependencies and run all test suites on node 14
name: Jest Tests
on:
    push:
        branches: ['**']
jobs:
    jest:
        runs-on: ubuntu-latest
        if: "github.repository_owner == 'gothub-team' && !contains(github.event.head_commit.message, 'ci skip')"
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Node
              uses: actions/setup-node@v4
              with:
                  node-version: 17.x
            - name: Install
              run: yarn install
            - name: Build
              run: yarn build
            - name: Unit Tests
              run: |
                  yarn test:util
                  yarn test:core
                  yarn test:store
                  yarn test:react
