# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    name: "Publish npm packages"
    runs-on: ubuntu-18.04
    if: "github.repository_owner == 'gothub-team' && contains(github.event.head_commit.message, '[release]')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{secrets.GH_PUSH_TOKEN}}
        fetch-depth: 0
    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: 17.x
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Publish
      run: yarn publish:all
      env:
        NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
