# This is a basic workflow to help you get started with Actions

name: prerelease

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:
    branches: []

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    name: "Publish npm packages as prerelease"
    runs-on: ubuntu-latest
    if: "github.repository_owner == 'gothub-team' && contains(github.event.head_commit.message, '[publish prerelease]')"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: 17.x
    - run: |
        git config --local user.email github-actions@github.com
        git config --local user.name github-actions
        yarn
        yarn build
        yarn bump:prerelease
        yarn publish:all:beta
        git push
      env:
        NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
